service: my-sls-service

provider:
  name: aws
  runtime: python3.7
  stackName: lambda-${self:service.name}
  tag: ${opt:tag}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "*"
      Resource: "arn:aws:s3:::somebucket/*"

functions:
  myFunc:
    name: myFunc
    tags:
      RESOURCE: lambda
      PUBLIC: false
      yor_trace: 64a1a480-550f-4ea6-904f-43138266594b
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "lambda:InvokeFunction"
        Resource:
          - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:invokedLambda"
    handler: Handler.handle
    timeout: 600
    memorySize: 320