service: my-sls-service

custom: ${file(customVars.json)}

provider:
  name: aws
  runtime: python3.7
  stackName: lambda-${self:service.name}
  tag: ${opt:tag}

  iamRoleStatements:
    - Effect: "Allow"
      Action: ${self:custom.my_sneaky_custom_var}
      Resource: ${self:custom.my_sneaky_custom_var}

functions:
  myFunc:
    name: myFunc-provider-level-with-var
    tags:
      RESOURCE: lambda
      PUBLIC: false
      yor_trace: 1873e3b9-bd8f-48b0-b03f-3ef6076e7a1d
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "lambda:InvokeFunction"
        Resource:
          - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:invokedLambda"
    handler: Handler.handle
    timeout: 600
    memorySize: 320