service: my-sls-service

provider:
  name: aws
  runtime: python3.7
  stackName: lambda-${self:service.name}
  tag: ${opt:tag}

  iamRoleStatements:
    # NOTE: This env value is set in test_AdminPolicyDocument
    - Effect: "Allow"
      Action: ${env:sneaky_var}
      Resource: ${env:sneaky_var}

functions:
  myFunc:
    name: myFunc-provider-level-with-var
    tags:
      RESOURCE: lambda
      PUBLIC: false
      yor_trace: 53bdf078-199b-4bd9-86e6-0d0314e2534e
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "lambda:InvokeFunction"
        Resource:
          - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:invokedLambda"
    handler: Handler.handle
    timeout: 600
    memorySize: 320