service: my-sls-service

provider:
  name: aws
  runtime: python3.7
  stackName: lambda-${self:service.name}
  tag: ${opt:tag}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::somebucket/*"

functions:
  myFunc:
    name: myFunc
    tags:
      RESOURCE: lambda
      PUBLIC: false
      yor_trace: ffd2401a-c982-4f12-9bd0-24ce9c94df43
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "lambda:InvokeFunction"
        Resource:
          - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:invokedLambda"
    handler: Handler.handle
    timeout: 600
    memorySize: 320
  myFunc2:
    name: myFunc
    tags:
      RESOURCE: lambda
      PUBLIC: false
      yor_trace: bf391bbe-8449-4f09-a267-feedf5ef4c07
    iamRoleStatementsName: ${self:custom.moduleName}-people-api-role-${self:provider.tag}
    iamRoleStatements:
      # add here the exact roles the lambda needs
    handler: Handler.handle
    timeout: 600
    memorySize: 320